print("------------python programming -----------------")
print("Day1:- print functions and introductions!")
print('To print new  line use this symbol ---->>>  "\n" There is it is the new line!! ')
print("Now let us see how to concatenating strings.")
print("Hello" + " " + "Getayawkal Befkadu ")
print("+++++input function++++++++")
print(" i guss u love " + input("what is the best programing language?"))